#!/usr/bin/env python3

import re
from gradelib import *

r = Runner(save("xv6.out"))

PTE_PRINT = """page table 0x9000000097fb0000
..0: pte 0x0000000097fab001 pa 0x0000000097fab000
.. ..0: pte 0x0000000097faa001 pa 0x0000000097faa000
.. .. ..0: pte 0x0000000097fa9001 pa 0x0000000097fa9000
.. .. .. ..0: pte 0x0000000097fac19f pa 0x0000000097fac000
.. .. .. ..1: pte 0x0000000097fa8193 pa 0x0000000097fa8000
.. .. .. ..2: pte 0x0000000097fa719f pa 0x0000000097fa7000
.. ..255: pte 0x0000000097faf001 pa 0x0000000097faf000
.. .. ..511: pte 0x0000000097fae001 pa 0x0000000097fae000
.. .. .. ..511: pte 0x0000000097fad001 pa 0x0000000097fad000
.. .. .. .. ..510: pte 0x4000000097fba091 pa 0x0000000097fba000
.. .. .. .. ..511: pte 0x4000000097fbb193 pa 0x0000000097fbb000"""

VAL_RE = "(0x00000000[0-9a-f]+)"
INDENT_RE = r"\s*\.\.\s*"
INDENT_ESC = "\\\s*\.\.\\\s*"

@test(0, "pgtbltest")
def test_pgtbltest():
    r.run_qemu(shell_script([
        'pgtbltest'
    ]), timeout=300)

@test(10, "pgtbltest: ugetpid", parent=test_pgtbltest)
def test_nettest_():
    r.match('^ugetpid_test: OK$')

@test(10, "pgtbltest: pgaccess", parent=test_pgtbltest)
def test_nettest_():
    r.match('^pgaccess_test: OK$')

@test(10, "pte printout")
def test_pteprint():
    first = True
    r.run_qemu(shell_script([
        'echo hi'
    ]))
    r.match('^hi')
    p = re.compile(VAL_RE)
    d = re.compile(INDENT_RE)
    for l in PTE_PRINT.splitlines():
        l = d.sub(INDENT_ESC, l)
        l = p.sub(VAL_RE, l)
        r.match(r'^{}$'.format(l))
        if first:
            first = False
        else:
            matches = re.findall(r'^{}$'.format(l), r.qemu.output, re.MULTILINE)
            assert_equal(len(matches[0]), 2)
            pa = (int(matches[0][0], 16) >> 10) << 12
            assert_equal(int(matches[0][1], 16), pa)

# @test(5, "answers-pgtbl.txt")
# def test_answers():
#     # just a simple sanity check, will be graded manually
#     check_answers("answers-pgtbl.txt")

@test(0, "usertests")
def test_usertests():
    r.run_qemu(shell_script([
        'usertests'
    ]), timeout=300)

@test(10, "usertests: all tests", parent=test_usertests)
def test_usertests():
    r.match('^ALL TESTS PASSED$')

# @test(1, "time")
# def test_time():
#     check_time()

run_tests()
